%token <word> WORD ASSIGNMENT_WORD REDIR_WORD
%token <number> NUMBER
%token AND_AND OR_OR GREATER_GREATER LESS_LESS

%type <command> inputunit command pipeline list simple_list simple_command
%type <redirect> redirection redirection_list
%type <element> simple_command_element
%type <word_list> word_list

%start inputunit

%left EOF
%left AND_AND OR_OR
%right '|'
%%

inputunit:	simple_list EOF
		|	error EOF
		|	EOF
		;

redirection:	'>' WORD
			|	'<' WORD
			|	NUMBER '>' WORD
			|	NUMBER '<' WORD
			|	REDIR_WORD '>' WORD
			|	REDIR_WORD '<' WORD
			|	GREATER_GREATER WORD
			|	NUMBER GREATER_GREATER WORD
			|	REDIR_WORD GREATER_GREATER WORD
			|	LESS_LESS WORD
			|	NUMBER LESS_LESS WORD
			|	REDIR_WORD LESS_LESS WORD
			;

simple_command_element: WORD
					|	ASSIGNMENT_WORD
					|	redirection
					;

redirection_list: redirection
			|	redirection_list redirection
			;

simple_command:	simple_command_element
			|	simple_command simple_command_element
			;

command:	simple_command
		|	'(' list ')'
		|	'(' list ')' redirection_list
		;

list:	list AND_AND list
	|	list OR_OR list
	|	pipeline
	;

simple_list:	simple_list AND_AND simple_list
			|	simple_list OR_OR simple_list
			|	pipeline
			;

pipeline:	pipeline '|' pipeline
		|	command
		;
%%
